/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GovernanceLibInterface extends ethers.utils.Interface {
  functions: {
    "addressOfPropoal(address,address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressOfPropoal",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressOfPropoal",
    data: BytesLike
  ): Result;

  events: {};
}

export class GovernanceLib extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GovernanceLibInterface;

  functions: {
    addressOfPropoal(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<[string] & { govAddress: string }>;

    "addressOfPropoal(address,address,string)"(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<[string] & { govAddress: string }>;
  };

  addressOfPropoal(
    factory: string,
    submitter: string,
    title: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "addressOfPropoal(address,address,string)"(
    factory: string,
    submitter: string,
    title: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addressOfPropoal(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "addressOfPropoal(address,address,string)"(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addressOfPropoal(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addressOfPropoal(address,address,string)"(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressOfPropoal(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressOfPropoal(address,address,string)"(
      factory: string,
      submitter: string,
      title: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
