/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface INFTGemPoolInterface extends ethers.utils.Interface {
  functions: {
    "collectClaim(uint256)": FunctionFragment;
    "createClaim(uint256)": FunctionFragment;
    "createClaims(uint256,uint256)": FunctionFragment;
    "createERC20Claim(address,uint256)": FunctionFragment;
    "createERC20Claims(address,uint256,uint256)": FunctionFragment;
    "initialize(string,string,uint256,uint256,uint256,uint256,uint256,address)": FunctionFragment;
    "mintGenesisGems(address,address)": FunctionFragment;
    "setFeeTracker(address)": FunctionFragment;
    "setGovernor(address)": FunctionFragment;
    "setMultiToken(address)": FunctionFragment;
    "setSwapHelper(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "collectClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaims",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createERC20Claim",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createERC20Claims",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintGenesisGems",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeTracker",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setGovernor", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMultiToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapHelper",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "collectClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createERC20Claim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createERC20Claims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintGenesisGems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMultiToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapHelper",
    data: BytesLike
  ): Result;

  events: {
    "NFTGemClaimCreated(address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "NFTGemClaimRedeemed(address,address,uint256,uint256,uint256)": EventFragment;
    "NFTGemCreated(address,address,uint256,uint256,uint256)": EventFragment;
    "NFTGemERC20ClaimCreated(address,address,uint256,uint256,address,uint256,uint256)": EventFragment;
    "NFTGemERC20ClaimRedeemed(address,address,uint256,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NFTGemClaimCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTGemClaimRedeemed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTGemCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTGemERC20ClaimCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTGemERC20ClaimRedeemed"): EventFragment;
}

export class INFTGemPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: INFTGemPoolInterface;

  functions: {
    collectClaim(
      claimHash: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "collectClaim(uint256)"(
      claimHash: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createClaim(
      timeframe: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "createClaim(uint256)"(
      timeframe: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    createClaims(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "createClaims(uint256,uint256)"(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    createERC20Claim(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createERC20Claim(address,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createERC20Claims(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createERC20Claims(address,uint256,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(string,string,uint256,uint256,uint256,uint256,uint256,address)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mintGenesisGems(
      creator: string,
      funder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintGenesisGems(address,address)"(
      creator: string,
      funder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setFeeTracker(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFeeTracker(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setGovernor(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setGovernor(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setMultiToken(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMultiToken(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSwapHelper(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSwapHelper(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  collectClaim(
    claimHash: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "collectClaim(uint256)"(
    claimHash: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createClaim(
    timeframe: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "createClaim(uint256)"(
    timeframe: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  createClaims(
    timeframe: BigNumberish,
    count: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "createClaims(uint256,uint256)"(
    timeframe: BigNumberish,
    count: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  createERC20Claim(
    erc20token: string,
    tokenAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createERC20Claim(address,uint256)"(
    erc20token: string,
    tokenAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createERC20Claims(
    erc20token: string,
    tokenAmount: BigNumberish,
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createERC20Claims(address,uint256,uint256)"(
    erc20token: string,
    tokenAmount: BigNumberish,
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BigNumberish,
    arg5: BigNumberish,
    arg6: BigNumberish,
    arg7: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(string,string,uint256,uint256,uint256,uint256,uint256,address)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BigNumberish,
    arg5: BigNumberish,
    arg6: BigNumberish,
    arg7: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mintGenesisGems(
    creator: string,
    funder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintGenesisGems(address,address)"(
    creator: string,
    funder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setFeeTracker(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setFeeTracker(address)"(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setGovernor(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setGovernor(address)"(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setMultiToken(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMultiToken(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSwapHelper(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSwapHelper(address)"(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    collectClaim(
      claimHash: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "collectClaim(uint256)"(
      claimHash: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createClaim(
      timeframe: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createClaim(uint256)"(
      timeframe: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createClaims(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createClaims(uint256,uint256)"(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createERC20Claim(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createERC20Claim(address,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createERC20Claims(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createERC20Claims(address,uint256,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(string,string,uint256,uint256,uint256,uint256,uint256,address)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: CallOverrides
    ): Promise<void>;

    mintGenesisGems(
      creator: string,
      funder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "mintGenesisGems(address,address)"(
      creator: string,
      funder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeTracker(addr: string, overrides?: CallOverrides): Promise<void>;

    "setFeeTracker(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernor(addr: string, overrides?: CallOverrides): Promise<void>;

    "setGovernor(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMultiToken(token: string, overrides?: CallOverrides): Promise<void>;

    "setMultiToken(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSwapHelper(addr: string, overrides?: CallOverrides): Promise<void>;

    "setSwapHelper(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    NFTGemClaimCreated(
      account: null,
      pool: null,
      claimHash: null,
      length: null,
      quantity: null,
      amountPaid: null
    ): EventFilter;

    NFTGemClaimRedeemed(
      account: null,
      pool: null,
      claimHash: null,
      amountPaid: null,
      feeAssessed: null
    ): EventFilter;

    NFTGemCreated(
      account: null,
      pool: null,
      claimHash: null,
      gemHash: null,
      quantity: null
    ): EventFilter;

    NFTGemERC20ClaimCreated(
      account: null,
      pool: null,
      claimHash: null,
      length: null,
      token: null,
      quantity: null,
      conversionRate: null
    ): EventFilter;

    NFTGemERC20ClaimRedeemed(
      account: null,
      pool: null,
      claimHash: null,
      token: null,
      ethPrice: null,
      tokenAmount: null,
      feeAssessed: null
    ): EventFilter;
  };

  estimateGas: {
    collectClaim(
      claimHash: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "collectClaim(uint256)"(
      claimHash: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createClaim(
      timeframe: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "createClaim(uint256)"(
      timeframe: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    createClaims(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "createClaims(uint256,uint256)"(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    createERC20Claim(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createERC20Claim(address,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createERC20Claims(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createERC20Claims(address,uint256,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(string,string,uint256,uint256,uint256,uint256,uint256,address)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    mintGenesisGems(
      creator: string,
      funder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintGenesisGems(address,address)"(
      creator: string,
      funder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setFeeTracker(addr: string, overrides?: Overrides): Promise<BigNumber>;

    "setFeeTracker(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setGovernor(addr: string, overrides?: Overrides): Promise<BigNumber>;

    "setGovernor(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setMultiToken(token: string, overrides?: Overrides): Promise<BigNumber>;

    "setMultiToken(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSwapHelper(addr: string, overrides?: Overrides): Promise<BigNumber>;

    "setSwapHelper(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    collectClaim(
      claimHash: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "collectClaim(uint256)"(
      claimHash: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createClaim(
      timeframe: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "createClaim(uint256)"(
      timeframe: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    createClaims(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "createClaims(uint256,uint256)"(
      timeframe: BigNumberish,
      count: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    createERC20Claim(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createERC20Claim(address,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createERC20Claims(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createERC20Claims(address,uint256,uint256)"(
      erc20token: string,
      tokenAmount: BigNumberish,
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(string,string,uint256,uint256,uint256,uint256,uint256,address)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mintGenesisGems(
      creator: string,
      funder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintGenesisGems(address,address)"(
      creator: string,
      funder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setFeeTracker(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFeeTracker(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setGovernor(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setGovernor(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setMultiToken(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMultiToken(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSwapHelper(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSwapHelper(address)"(
      addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
