/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockProxyRegistryInterface extends ethers.utils.Interface {
  functions: {
    "proxies(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "proxies", values: [string]): string;

  decodeFunctionResult(functionFragment: "proxies", data: BytesLike): Result;

  events: {};
}

export class MockProxyRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockProxyRegistryInterface;

  functions: {
    proxies(input: string, overrides?: Overrides): Promise<ContractTransaction>;

    "proxies(address)"(
      input: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  proxies(input: string, overrides?: Overrides): Promise<ContractTransaction>;

  "proxies(address)"(
    input: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    proxies(input: string, overrides?: CallOverrides): Promise<string>;

    "proxies(address)"(
      input: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    proxies(input: string, overrides?: Overrides): Promise<BigNumber>;

    "proxies(address)"(
      input: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    proxies(
      input: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "proxies(address)"(
      input: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
