/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockQueryHelperInterface extends ethers.utils.Interface {
  functions: {
    "COIN()": FunctionFragment;
    "coinQuote(address,uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "getPair(address,address)": FunctionFragment;
    "getPathForCoinToToken(address)": FunctionFragment;
    "getReserves(address)": FunctionFragment;
    "hasPool(address)": FunctionFragment;
    "setFactory(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "COIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "coinQuote",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPathForCoinToToken",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getReserves", values: [string]): string;
  encodeFunctionData(functionFragment: "hasPool", values: [string]): string;
  encodeFunctionData(functionFragment: "setFactory", values: [string]): string;

  decodeFunctionResult(functionFragment: "COIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "coinQuote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPathForCoinToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;

  events: {};
}

export class MockQueryHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockQueryHelperInterface;

  functions: {
    COIN(overrides?: CallOverrides): Promise<[string] & { weth: string }>;

    "COIN()"(overrides?: CallOverrides): Promise<[string] & { weth: string }>;

    coinQuote(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        ethereum: BigNumber;
        tokenReserve: BigNumber;
        ethReserve: BigNumber;
      }
    >;

    "coinQuote(address,uint256)"(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        ethereum: BigNumber;
        tokenReserve: BigNumber;
        ethReserve: BigNumber;
      }
    >;

    factory(overrides?: CallOverrides): Promise<[string] & { fac: string }>;

    "factory()"(overrides?: CallOverrides): Promise<[string] & { fac: string }>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string] & { pair: string }>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string] & { pair: string }>;

    getPathForCoinToToken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "getPathForCoinToToken(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getReserves(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;

    "getReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;

    hasPool(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "hasPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setFactory(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setFactory(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  COIN(overrides?: CallOverrides): Promise<string>;

  "COIN()"(overrides?: CallOverrides): Promise<string>;

  coinQuote(
    arg0: string,
    tokenAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      ethereum: BigNumber;
      tokenReserve: BigNumber;
      ethReserve: BigNumber;
    }
  >;

  "coinQuote(address,uint256)"(
    arg0: string,
    tokenAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      ethereum: BigNumber;
      tokenReserve: BigNumber;
      ethReserve: BigNumber;
    }
  >;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  getPair(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getPair(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getPathForCoinToToken(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "getPathForCoinToToken(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getReserves(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
  >;

  "getReserves(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
  >;

  hasPool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "hasPool(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  setFactory(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setFactory(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    COIN(overrides?: CallOverrides): Promise<string>;

    "COIN()"(overrides?: CallOverrides): Promise<string>;

    coinQuote(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        ethereum: BigNumber;
        tokenReserve: BigNumber;
        ethReserve: BigNumber;
      }
    >;

    "coinQuote(address,uint256)"(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        ethereum: BigNumber;
        tokenReserve: BigNumber;
        ethReserve: BigNumber;
      }
    >;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getPathForCoinToToken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getPathForCoinToToken(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getReserves(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;

    "getReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;

    hasPool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "hasPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setFactory(arg0: string, overrides?: CallOverrides): Promise<void>;

    "setFactory(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    COIN(overrides?: CallOverrides): Promise<BigNumber>;

    "COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

    coinQuote(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "coinQuote(address,uint256)"(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPathForCoinToToken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPathForCoinToToken(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReserves(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasPool(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "hasPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFactory(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "setFactory(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    COIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "COIN()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    coinQuote(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "coinQuote(address,uint256)"(
      arg0: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPair(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPair(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPathForCoinToToken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPathForCoinToToken(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserves(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReserves(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasPool(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasPool(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFactory(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setFactory(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
