/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITransferPoolFundsProposalData } from "../ITransferPoolFundsProposalData";

export class ITransferPoolFundsProposalData__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransferPoolFundsProposalData {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITransferPoolFundsProposalData;
  }
}

const _abi = [
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
