/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, BigNumberish } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { MintPoolGemsProposalData } from "../MintPoolGemsProposalData";

export class MintPoolGemsProposalData__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _pool: string,
    _destination: string,
    _quantity: BigNumberish,
    overrides?: Overrides
  ): Promise<MintPoolGemsProposalData> {
    return super.deploy(
      _pool,
      _destination,
      _quantity,
      overrides || {}
    ) as Promise<MintPoolGemsProposalData>;
  }
  getDeployTransaction(
    _pool: string,
    _destination: string,
    _quantity: BigNumberish,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(
      _pool,
      _destination,
      _quantity,
      overrides || {}
    );
  }
  attach(address: string): MintPoolGemsProposalData {
    return super.attach(address) as MintPoolGemsProposalData;
  }
  connect(signer: Signer): MintPoolGemsProposalData__factory {
    return super.connect(signer) as MintPoolGemsProposalData__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MintPoolGemsProposalData {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MintPoolGemsProposalData;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161014b38038061014b8339818101604052606081101561003357600080fd5b5080516020820151604090920151600080546001600160a01b039384166001600160a01b031991821617909155600180549390941692169190911790915560025560c9806100826000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806373d4a13a14602d575b600080fd5b6033606a565b6040805173ffffffffffffffffffffffffffffffffffffffff94851681529290931660208301528183015290519081900360600190f35b60005460015460025473ffffffffffffffffffffffffffffffffffffffff92831693929091169156fea2646970667358221220efb9203e61ae75d1f055c1ca09a9d423d32ae0750e80381e70e3139cfbd6a48c64736f6c63430007030033";
